#Este es el segundo workflow que construira la aplicacion

name: build

on:
    push: 
        branches: ["main", "testing_pr"] #se pueden poner varias branches usando corchetes separados por coma
        #si en lugar de un branch se necesita un archivo se puede utilizar el keyword paths:

    workflow_dispatch: 

jobs: 

    build-phase:

        runs-on: ubuntu-latest

        steps:

            - name: Checkout
              uses: actions/checkout@v4

            - name: Installing Java
              uses: actions/setup-java@v4
              with:
                distribution: 'temurin'
                java-version: '17'
            
            - name: Building step
              run: ./gradlew build

            - run: mkdir -p path/to/artifact
            - run: echo hello > path/to/artifact/world.txt
            - uses: actions/upload-artifact@v4
              with:
                name: my-artifact
                path: path/to/artifact/world.txt