#Este es el segundo workflow que construira la aplicacion

name: build

on:
    push: 
        branches: ["main"] #se pueden poner varias branches usando corchetes separados por coma
        #si en lugar de un branch se necesita un archivo se puede utilizar el keyword paths:

    workflow_dispatch: 

#variables de ambiente de workflow
env: 
  my-secret: ${{ secrets.REGION_SECRET }}
  my-city: ${{ vars.CITY }}

jobs: 

  unit-testing-phase:

    if: ${{ vars.CITY == 'NEW YORK' }}

    runs-on: ubuntu-latest

    steps:

        - name: Checkout
          uses: actions/checkout@v4

        - name: Installing Java
          uses: actions/setup-java@v4
          with:
            distribution: 'temurin'
            java-version: '17'
        
          #this step is to run the task that is already defined inside the project
        - name: Execute test task
          run: ./gradlew test

        # - name: Adding Sleep
        #   run: sleep 2m

        - name: Print env variables
          run: | 
            echo ${{ env.version }}
            echo ${{ env.app_name }}
          env:
            version: 2.0
            app_name: "peacegame"

        # - name: Print env variables second way
        #   run: | 
        #     echo $version
        #     echo $app_name
        #   env:
        #     version: 2.0
        #     app_name: "peacegame"

        - name: Export env variable
          run: echo "type=rock" >> $GITHUB_ENV

        - name: Printing variable
          run: echo ${{env.type}}

  build-phase:
        
        needs: ['unit-testing-phase']
        runs-on: ubuntu-latest

        steps:

            - name: Checkout
              uses: actions/checkout@v4

            - name: Installing Java
              uses: actions/setup-java@v4
              with:
                distribution: 'temurin'
                java-version: '17'
            
            - name: Building step
              run: ./gradlew assemble

            - uses: actions/upload-artifact@v4
              with:
                name: my-artifact
                path: build/libs/java17-examples-0.0.1-snapshot.jar