#Este es el primer workflow que se aconseja crear al iniciar un proyecto

name: unit-testing

on:
    pull_request:

    workflow_dispatch:

concurrency:
  group: 'pull-request-group'
  cancel-in-progress: true

jobs: 

    unit-testing-phase:

        runs-on: ubuntu-latest

        steps:

            - name: Checkout
              uses: actions/checkout@v4

            - name: Installing Java
              uses: actions/setup-java@v4
              with:
                distribution: 'temurin'
                java-version: '17'
            
              #this step is to run the task that is already defined inside the project
            - name: Execute test task
              run: ./gradlew test

            - name: Adding Sleep
              run: sleep 5m